### PR TITLE
Mark new symbols in ROCm 5.7.0 as global

### LINKED ISSUE #89: Missing symbols in 5.7.0 release
Hi! I'm packaging ROCm for Arch Linux. The new release of `hsa-rocr` now calls functions like `hsaKmtWaitOnEvent_Ext` or `hsaKmtReplaceAsanHeaderPage`. However, these functions are not part of version 5.7.0: I couldn't find matching declarations or definitions in the source code.

Example output when building rocminfo:
```
/usr/bin/ld: /opt/rocm/lib/libhsa-runtime64.so.1.11.0: undefined reference to `hsaKmtWaitOnMultipleEvents_Ext'
/usr/bin/ld: /opt/rocm/lib/libhsa-runtime64.so.1.11.0: undefined reference to `hsaKmtReplaceAsanHeaderPage'
/usr/bin/ld: /opt/rocm/lib/libhsa-runtime64.so.1.11.0: undefined reference to `hsaKmtWaitOnEvent_Ext'
```

Note that the static library in the ubuntu package _does_ include the symbols:
```
nm /opt/rocm-5.7.0/lib/libhsakmt.a | grep -E "_Ext|Asan"
0000000000001200 T hsaKmtWaitOnEvent_Ext
0000000000000970 T hsaKmtWaitOnMultipleEvents_Ext
0000000000001430 T hsaKmtReplaceAsanHeaderPage
0000000000001440 T hsaKmtReturnAsanHeaderPage
```

Where do I find correct source code?

### PR DESCRIPTION
**Pull request by tpkessler**
Fixes #89

### CODE REVIEW

**Comment by Mystro256** [comment]
This is merged into 6.0, but looks like there's a new one:
hsaKmtGetAMDGPUDeviceHandle

I spoke to @kentrussell and I believe he said that they're merging this source code into rocr-runtime around the 6.1 release, so it won't be an issue soon.

**Comment by Mystro256** [comment]
E.g. this worked for me:

```
diff --git a/src/libhsakmt.ver b/src/libhsakmt.ver
index 15c2916..c04cefe 100644
--- a/src/libhsakmt.ver
+++ b/src/libhsakmt.ver
@@ -81,6 +81,7 @@ hsaKmtWaitOnEvent_Ext;
 hsaKmtWaitOnMultipleEvents_Ext;
 hsaKmtReplaceAsanHeaderPage;
 hsaKmtReturnAsanHeaderPage;
+hsaKmtGetAMDGPUDeviceHandle;
 
 local: *;
 };
```

If this is really going away in 6.1, then there's probably no point to patch it.

**Comment by tpkessler** [comment]
Thanks for the update, @Mystro256! I can confirm that `hsa-rocr` and `rocminfo` build fine with this patch. Given that this repo will become obsolete soon, I will close this PR.

**Comment by Mystro256** [comment]
Hi, See a4d46eb769313ddfdc238fdd358519f1c56bfa1f, you can apply that to 6.0 to make it work.

@kentrussell merged it in for me :)
He also said it's a bit in the air when this repo will be obsoleted, but it will be one of the future 6.x releases.

**Pull request closed without merging**
